version: '3.8'

services:
  app:
    container_name: cragheads-projects-api
    restart: always
    build: .
    ports:
      - "3020:3020"
    environment:
      - DB_CONN_STRING=mongodb://mongodb:27017/cragheads-db
      - PORT=3020
    depends_on:
      - mongodb
    volumes:
      - .:/app
    networks:
      - cragheads-projects-network
    
  # mongodb:
  #   container_name: cragheads-climbs-mongo
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./data:/data/db
  #   networks:
  #     - cragheads-climbs-network

  

networks:
  cragheads-projects-network:
    driver: bridge